### ISSUE TITLE
Adapt `read_vpts()`and VPTS object to VPTS CSV format

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#551]
## [Current functionality](https://adriaandokter.com/bioRad/reference/read_vpts.html)

Read a time series of vertical profiles (`vpts`) from file

```R
read_vpts(
  file,
  radar,
  lat,
  lon,
  height,
  wavelength = "C"
)
```

## Reason for change

- [VPTS CSV](https://aloftdata.eu/vpts-csv/) is now a standardized format for VPTS data. We need a function to read that data
- It is intended to replace the "A text file containing the standard output (stdout) generated by vol2bird (or the package function `calculate_vp`)."

## Questions

- [ ] Should data be converted to VPTS object or remain a data frame? This depends on whether we want to keep vpts objects around or make those regular data frames. @adokter 
- [ ] VPTS objects have some conventions regarding column order and names. I think those should be adopted in VPTS (data frames).
- [ ] Should it be possible to read from a URL in addition to single file path (supported by readr)
- [ ] Should we still support the legacy `stdout` objects? That requires keeping around all the parameters too.

## Todo

- [ ] Remove `lat` parameter. It is included in data as `radar_latitude`
- [ ] Remove `long` parameter. It is included in data as `radar_longitude`
- [ ] Remove `height` parameter. It is included in data as `radar_height`
- [ ] Remove `wavelength` parameter. It is included in data as `radar_wavelength`
- [ ] Allow to read a list of file paths, rather than single `file`. Those files will be combined.
- [ ] Add `readr` as dependency
